export interface Record {
    id?: number
    activeFranchise?: number
    activeOpponentFranchise?: number
    franchiseName?: string
    gameTypeId?: number
    homeGamesPlayed?: number
    homeGoalsAgainst?: number
    homeGoalsFor?: number
    homeLastMeetingSeasonId?: number
    homeLosses?: number
    homeOtLosses?: number
    homePoints?: number
    homeTies?: number
    homeWins?: number
    opponentFranchiseId?: number
    opponentFranchiseName?: string
    opponentTeamId?: number
    roadGamesPlayed?: number
    roadGoalsAgainst?: number
    roadGoalsFor?: number
    roadLastMeetingSeasonId?: number
    roadLosses?: number
    roadOtLosses?: number
    roadPoints?: number
    roadTies?: number
    roadWins?: number
    teamFranchiseId?: number
    teamId?: number
    totalGamesPlayed?: number
    totalGoalsAgainst?: number
    totalGoalsFor?: number
    totalLastMeetingSeasonId?: number
    totalLosses?: number
    totalOtLosses?: number
    totalPoints?: number
    totalTies?: number
    totalWins?: number
}
